version: '3.8'

networks:
  custom_network:
    external: true
    name: nest-kafka-poc-network

services:
  app:
    image: node:18.19.1-alpine
    container_name: nestjs-kafka-poc
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run start:dev"
    networks:
      - custom_network
